-- 1
SELECT count(*) FROM FORNECEDOR;

-- 2
SELECT SUM(prodvlrunitario), AVG(prodvlrunitario), MAX(prodvlrunitario), MIN(prodvlrunitario)
FROM PRODUTO;

-- 3
SELECT * FROM CLIENTE WHERE clitelefone IS NULL;

-- 4
SELECT COUNT(*)
FROM PRODUTOS
GROUP BY IDFORNECEDOR
ORDER BY IDFORNECEDOR;

-- 5
SELECT SUM(prodvlrunitario)
FROM PRODUTOS
GROUP BY IDFORNECEDOR;

-- 6
SELECT COUNT(*)
JOIN CLIENTE ON NOTAFISCAL.IDCLIENTE = CLIENTE.IDCLIENTE
GROUP BY IDCLIENTE
ORDER BY CLINOME;

-- 7
SELECT SUM(valorunitario * QUANTIDADE) AS TOTAL
FROM NOTADETALHE
GROUP BY IDNOTAFISCAL;

-- 8
SELECT SUM(valorunitario * QUANTIDADE) AS TOTAL
FROM NOTADETALHE
JOIN NOTAFISCAL on NOTADETALHE.IDNOTAFISCAL = NOTAFISCAL.ID
JOIN CLIENTE on NOTAFISCAL.IDCLIENTE = CLIENTE.ID
GROUP BY CLIENTE.CLINOME
ORDER BY CLIENTE.CLINOME;

-- 9
SELECT SUM(valorunitario * QUANTIDADE) AS TOTAL
FROM NOTADETALHE
JOIN NOTAFISCAL on NOTADETALHE.IDNOTAFISCAL = NOTAFISCAL.ID
JOIN CLIENTE on NOTAFISCAL.IDCLIENTE = CLIENTE.ID
WHERE notadetalhe.valor * notadetalhe.quantidade > 20
GROUP BY CLIENTE.CLINOME
ORDER BY CLIENTE.CLINOME;

-- 10
SELECT SUM(valorunitario * QUANTIDADE) AS TOTAL
FROM NOTADETALHE
JOIN NOTAFISCAL on NOTADETALHE.IDNOTAFISCAL = NOTAFISCAL.ID
JOIN CLIENTE on NOTAFISCAL.IDCLIENTE = CLIENTE.ID
WHERE notadetalhe.valor * notadetalhe.quantidade > 20
AND NOTAFISCAL.NOTAEMISSAO BETWEEN '2011-01-01' AND '2012-01-1' 
GROUP BY CLIENTE.CLINOME
ORDER BY CLIENTE.CLINOME;

